### ISSUE TITLE
Problem przy instalacji

### ISSUE THREAD

**Issue by skuteli** [DanePubliczneGovPl/ckanext-danepubliczne#225]
(ckan) skuteli@giada:/home/ckan$ pip install -r /home/ckan/src/ckanext-archiver/pip-requirements.txt 
Invalid requirement: 'celery==2.4.2,'
Traceback (most recent call last):
  File "/home/skuteli/.virtualenvs/ckan/local/lib/python2.7/site-packages/pip/req/req_install.py", line 78, in __init__
    req = Requirement(req)
  File "/home/skuteli/.virtualenvs/ckan/local/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "u','"

**Comment by skuteli** [comment]
Po usunięciu przecinków kończących linię z /home/ckan/src/ckanext-archiver/pip-requirements.txt udaje się zainstalować
