### ISSUE TITLE
TypeError: $(...).fileupload is not a function 

### ISSUE THREAD

**Issue by achyuth8121** [DanePubliczneGovPl/ckanext-danepubliczne#236]
While integrating the file upload it is throwing error(Uploading file type is video-audio).

**Comment by achyuth8121** [comment]
Can anyone please help as it is very much needed help.

Thanks in advance if anyone can give a quick glance..

**Comment by achyuth8121** [comment]
Full error message below. 

angular.js?fp=1467881266272:10126 TypeError: $(...).fileupload is not a function
    at HTMLDocument.eval (eval at globalEval (http://localhost/shrpa-prototype/client/vendor/jquery/dist/jquery.min.js:2:2538), <anonymous>:4:21)
    at j (eval at globalEval (http://localhost/shrpa-prototype/client/vendor/jquery/dist/jquery.min.js:2:2538), <anonymous>:2:27309)
    at Object.add [as done] (eval at globalEval (http://localhost/shrpa-prototype/client/vendor/jquery/dist/jquery.min.js:2:2538), <anonymous>:2:27618)
    at m.fn.ready (eval at globalEval (http://localhost/shrpa-prototype/client/vendor/jquery/dist/jquery.min.js:2:2538), <anonymous>:2:29724)
    at m.fn.init (eval at globalEval (http://localhost/shrpa-prototype/client/vendor/jquery/dist/jquery.min.js:2:2538), <anonymous>:2:24735)
    at m (eval at globalEval (http://localhost/shrpa-prototype/client/vendor/jquery/dist/jquery.min.js:2:2538), <anonymous>:2:393)
    at eval (eval at globalEval (http://localhost/shrpa-prototype/client/vendor/jquery/dist/jquery.min.js:2:2538), <anonymous>:1:1)
    at Function.globalEval (http://localhost/shrpa-prototype/client/vendor/jquery/dist/jquery.min.js:2:2538)
    at n.domManip (http://localhost/shrpa-prototype/client/vendor/jquery/dist/jquery.min.js:3:17225)
    at n.append (http://localhost/shrpa-prototype/client/vendor/jquery/dist/jquery.min.js:3:14908) <div ng-include="'client/assets/views/videoFileUpload.html'" class="ng-scope">

**Comment by KrzysztofMadejski** [comment]
It has been fixed in #220, so it should work in latest develop

**Comment by KrzysztofMadejski** [comment]
@achyuth8121, can I close it?

**Comment by achyuth8121** [comment]
Yes please..

Thank you.
