### ISSUE TITLE
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Class 'kombu.transport.sqlalchemy.models.Message' is not mapped

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#285]
Błąd pojawia się losowo. Zgłaszany także przez innych: https://github.com/ckan/ckan/issues/2277
Powiązany zapewne z https://github.com/ckan/ckanext-qa/issues/22.

```
[Thu Feb 02 10:47:47.235708 2017] [:error] [pid 29232] [remote 163.172.64.220:55868] mod_wsgi (pid=29232): Exception occurred processing WSGI script '/etc/ckan/ckan.py'.
[Thu Feb 02 10:47:47.235741 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]             </p>Traceback (most recent call last):
[Thu Feb 02 10:47:47.235765 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/config/middleware.py", line 362, in __call__
[Thu Feb 02 10:47:47.235802 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return self.app(environ, start_response)
[Thu Feb 02 10:47:47.235824 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/paste/cascade.py", line 130, in __call__
[Thu Feb 02 10:47:47.235856 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return self.apps[-1](environ, start_response)
[Thu Feb 02 10:47:47.235877 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/config/middleware.py", line 226, in __call__
[Thu Feb 02 10:47:47.235908 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return self.app(environ, start_response)
[Thu Feb 02 10:47:47.235927 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
[Thu Feb 02 10:47:47.235945 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     app_iter = self.application(environ, start_response)
[Thu Feb 02 10:47:47.235958 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/repoze/who/middleware.py", line 87, in __call__
[Thu Feb 02 10:47:47.235991 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     app_iter = app(environ, wrapper.wrap_start_response)
[Thu Feb 02 10:47:47.236007 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/middleware.py", line 214, in __call__
[Thu Feb 02 10:47:47.236034 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     self.app, new_environ, catch_exc_info=True)
[Thu Feb 02 10:47:47.236048 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/util.py", line 94, in call_wsgi_application
[Thu Feb 02 10:47:47.236065 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     app_iter = application(environ, start_response)
[Thu Feb 02 10:47:47.236077 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/weberror/errormiddleware.py", line 156, in __call__
[Thu Feb 02 10:47:47.236093 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return self.application(environ, start_response)
[Thu Feb 02 10:47:47.236105 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
[Thu Feb 02 10:47:47.236121 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     resp = self.call_func(req, *args, **self.kwargs)
[Thu Feb 02 10:47:47.236133 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
[Thu Feb 02 10:47:47.236147 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return self.func(req, *args, **kwargs)
[Thu Feb 02 10:47:47.236159 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
[Thu Feb 02 10:47:47.236175 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return request.get_response(self.app)
[Thu Feb 02 10:47:47.236187 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
[Thu Feb 02 10:47:47.236203 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     application, catch_exc_info=False)
[Thu Feb 02 10:47:47.236215 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
[Thu Feb 02 10:47:47.236229 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     app_iter = application(self.environ, start_response)
[Thu Feb 02 10:47:47.236241 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
[Thu Feb 02 10:47:47.236255 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     resp = self.call_func(req, *args, **self.kwargs)
[Thu Feb 02 10:47:47.236267 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
[Thu Feb 02 10:47:47.236282 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return self.func(req, *args, **kwargs)
[Thu Feb 02 10:47:47.236294 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
[Thu Feb 02 10:47:47.236309 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     response = request.get_response(self.app)
[Thu Feb 02 10:47:47.236323 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
[Thu Feb 02 10:47:47.236350 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     application, catch_exc_info=False)
[Thu Feb 02 10:47:47.236377 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
[Thu Feb 02 10:47:47.236404 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     app_iter = application(self.environ, start_response)
[Thu Feb 02 10:47:47.236419 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/beaker/middleware.py", line 73, in __call__
[Thu Feb 02 10:47:47.236435 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return self.app(environ, start_response)
[Thu Feb 02 10:47:47.236447 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/beaker/middleware.py", line 155, in __call__
[Thu Feb 02 10:47:47.236461 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return self.wrap_app(environ, session_start_response)
[Thu Feb 02 10:47:47.236479 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/routes/middleware.py", line 131, in __call__
[Thu Feb 02 10:47:47.236504 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     response = self.app(environ, start_response)
[Thu Feb 02 10:47:47.236520 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/wsgiapp.py", line 125, in __call__
[Thu Feb 02 10:47:47.236545 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     response = self.dispatch(controller, environ, start_response)
[Thu Feb 02 10:47:47.236559 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/wsgiapp.py", line 324, in dispatch
[Thu Feb 02 10:47:47.236574 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return controller(environ, start_response)
[Thu Feb 02 10:47:47.236586 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/base.py", line 338, in __call__
[Thu Feb 02 10:47:47.236602 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     res = WSGIController.__call__(self, environ, start_response)
[Thu Feb 02 10:47:47.236614 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/controllers/core.py", line 217, in __call__
[Thu Feb 02 10:47:47.236630 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     response = self._inspect_call(self.__before__)
[Thu Feb 02 10:47:47.236642 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/controllers/core.py", line 107, in _inspect_call
[Thu Feb 02 10:47:47.236656 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     result = self._perform_call(func, args)
[Thu Feb 02 10:47:47.236668 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/controllers/core.py", line 60, in _perform_call
[Thu Feb 02 10:47:47.236683 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return func(**args)
[Thu Feb 02 10:47:47.236695 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/base.py", line 240, in __before__
[Thu Feb 02 10:47:47.236710 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     app_globals.app_globals._check_uptodate()
[Thu Feb 02 10:47:47.236722 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/app_globals.py", line 183, in _check_uptodate
[Thu Feb 02 10:47:47.236737 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     value = model.get_system_info('ckan.config_update')
[Thu Feb 02 10:47:47.236750 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/model/system_info.py", line 31, in get_system_info
[Thu Feb 02 10:47:47.236774 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     obj = meta.Session.query(SystemInfo).filter_by(key=key).first()
[Thu Feb 02 10:47:47.236786 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
[Thu Feb 02 10:47:47.236803 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return getattr(self.registry(), name)(*args, **kwargs)
[Thu Feb 02 10:47:47.236815 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1155, in query
[Thu Feb 02 10:47:47.236831 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     return self._query_cls(entities, self, **kwargs)
[Thu Feb 02 10:47:47.236843 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 106, in __init__
[Thu Feb 02 10:47:47.236858 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     self._set_entities(entities)
[Thu Feb 02 10:47:47.236870 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 116, in _set_entities
[Thu Feb 02 10:47:47.236884 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     self._set_entity_selectables(self._entities)
[Thu Feb 02 10:47:47.236896 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 149, in _set_entity_selectables
[Thu Feb 02 10:47:47.236911 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     ent.setup_entity(*d[entity])
[Thu Feb 02 10:47:47.236922 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2987, in setup_entity
[Thu Feb 02 10:47:47.236937 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     self._with_polymorphic = ext_info.with_polymorphic_mappers
[Thu Feb 02 10:47:47.236949 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 712, in __get__
[Thu Feb 02 10:47:47.236965 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     obj.__dict__[self.__name__] = result = self.fget(obj)
[Thu Feb 02 10:47:47.236977 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1865, in _with_polymorphic_mappers
[Thu Feb 02 10:47:47.236993 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     configure_mappers()
[Thu Feb 02 10:47:47.237005 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2566, in configure_mappers
[Thu Feb 02 10:47:47.237019 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     raise e
[Thu Feb 02 10:47:47.237037 2017] [:error] [pid 29232] [remote 163.172.64.220:55868] InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Class 'kombu.transport.sqlalchemy.models.Message' is not mapped
^C
kmadejski@dp-prod-v5:~$ sudo apachectl restart
[sudo] password for kmadejski:
kmadejski@dp-prod-v5:~$ tail -f /var/log/ckan/ckan.error.log
[Thu Feb 02 10:47:47.236965 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     obj.__dict__[self.__name__] = result = self.fget(obj)
[Thu Feb 02 10:47:47.236977 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1865, in _with_polymorphic_mappers
[Thu Feb 02 10:47:47.236993 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     configure_mappers()
[Thu Feb 02 10:47:47.237005 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2566, in configure_mappers
[Thu Feb 02 10:47:47.237019 2017] [:error] [pid 29232] [remote 163.172.64.220:55868]     raise e
[Thu Feb 02 10:47:47.237037 2017] [:error] [pid 29232] [remote 163.172.64.220:55868] InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Class 'kombu.transport.sqlalchemy.models.Message' is not mapped
```

**Comment by KrzysztofMadejski** [comment]
Po wdrożeniu redisa, już nie powinno się pojawić.
