### ISSUE TITLE
Solr returned an error: 400 Illegal character ((CTRL-CHAR, code 1)) 

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#296]
Do zdiagnozowania na przykładzie (Magdalena Ragus).

```
[Mon Mar 27 11:21:28.141050 2017] [:error] [pid 19627] [remote ip1] URL: https://danepubliczne.gov.pl/dataset/new_resource/plan-dzialania-pot-na-lata-2017-2018
[Mon Mar 27 11:21:28.141062 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/weberror/errormiddleware.py', line 162 in __call__
[Mon Mar 27 11:21:28.141068 2017] [:error] [pid 19627] [remote ip1]   app_iter = self.application(environ, sr_checker)
[Mon Mar 27 11:21:28.141072 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
[Mon Mar 27 11:21:28.141077 2017] [:error] [pid 19627] [remote ip1]   resp = self.call_func(req, *args, **self.kwargs)
[Mon Mar 27 11:21:28.141081 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Mon Mar 27 11:21:28.141086 2017] [:error] [pid 19627] [remote ip1]   return self.func(req, *args, **kwargs)
[Mon Mar 27 11:21:28.141091 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
[Mon Mar 27 11:21:28.141095 2017] [:error] [pid 19627] [remote ip1]   return request.get_response(self.app)
[Mon Mar 27 11:21:28.141100 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Mon Mar 27 11:21:28.141105 2017] [:error] [pid 19627] [remote ip1]   application, catch_exc_info=False)
[Mon Mar 27 11:21:28.141109 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Mon Mar 27 11:21:28.141114 2017] [:error] [pid 19627] [remote ip1]   app_iter = application(self.environ, start_response)
[Mon Mar 27 11:21:28.141118 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
[Mon Mar 27 11:21:28.141123 2017] [:error] [pid 19627] [remote ip1]   resp = self.call_func(req, *args, **self.kwargs)
[Mon Mar 27 11:21:28.141127 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Mon Mar 27 11:21:28.141132 2017] [:error] [pid 19627] [remote ip1]   return self.func(req, *args, **kwargs)
[Mon Mar 27 11:21:28.141137 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
[Mon Mar 27 11:21:28.141142 2017] [:error] [pid 19627] [remote ip1]   response = request.get_response(self.app)
[Mon Mar 27 11:21:28.141146 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Mon Mar 27 11:21:28.141151 2017] [:error] [pid 19627] [remote ip1]   application, catch_exc_info=False)
[Mon Mar 27 11:21:28.141156 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Mon Mar 27 11:21:28.141160 2017] [:error] [pid 19627] [remote ip1]   app_iter = application(self.environ, start_response)
[Mon Mar 27 11:21:28.141165 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
[Mon Mar 27 11:21:28.141169 2017] [:error] [pid 19627] [remote ip1]   return self.app(environ, start_response)
[Mon Mar 27 11:21:28.141182 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
[Mon Mar 27 11:21:28.141197 2017] [:error] [pid 19627] [remote ip1]   return self.wrap_app(environ, session_start_response)
[Mon Mar 27 11:21:28.141201 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
[Mon Mar 27 11:21:28.141206 2017] [:error] [pid 19627] [remote ip1]   response = self.app(environ, start_response)
[Mon Mar 27 11:21:28.141211 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
[Mon Mar 27 11:21:28.141215 2017] [:error] [pid 19627] [remote ip1]   response = self.dispatch(controller, environ, start_response)
[Mon Mar 27 11:21:28.141220 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
[Mon Mar 27 11:21:28.141225 2017] [:error] [pid 19627] [remote ip1]   return controller(environ, start_response)
[Mon Mar 27 11:21:28.141229 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/base.py', line 338 in __call__
[Mon Mar 27 11:21:28.141234 2017] [:error] [pid 19627] [remote ip1]   res = WSGIController.__call__(self, environ, start_response)
[Mon Mar 27 11:21:28.141238 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
[Mon Mar 27 11:21:28.141243 2017] [:error] [pid 19627] [remote ip1]   response = self._dispatch_call()
[Mon Mar 27 11:21:28.141248 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
[Mon Mar 27 11:21:28.141253 2017] [:error] [pid 19627] [remote ip1]   response = self._inspect_call(func)
[Mon Mar 27 11:21:28.141257 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
[Mon Mar 27 11:21:28.141262 2017] [:error] [pid 19627] [remote ip1]   result = self._perform_call(func, args)
[Mon Mar 27 11:21:28.141267 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
[Mon Mar 27 11:21:28.141271 2017] [:error] [pid 19627] [remote ip1]   return func(**args)
[Mon Mar 27 11:21:28.141276 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckanext-danepubliczne/ckanext/danepubliczne/controllers/package.py', line 826 in new_resource
[Mon Mar 27 11:21:28.141281 2017] [:error] [pid 19627] [remote ip1]   return super(PackageController, self).new_resource(id, data, errors, error_summary)
[Mon Mar 27 11:21:28.141288 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/controllers/package.py', line 702 in new_resource
[Mon Mar 27 11:21:28.141292 2017] [:error] [pid 19627] [remote ip1]   dict(data_dict, state='active'))

[Mon Mar 27 11:21:28.141288 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/controllers/package.py', line 702 in new_resource
[Mon Mar 27 11:21:28.141292 2017] [:error] [pid 19627] [remote ip1]   dict(data_dict, state='active'))
[Mon Mar 27 11:21:28.141297 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/logic/__init__.py', line 424 in wrapped
[Mon Mar 27 11:21:28.141302 2017] [:error] [pid 19627] [remote ip1]   result = _action(context, data_dict, **kw)
[Mon Mar 27 11:21:28.141306 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/logic/action/update.py', line 388 in package_update
[Mon Mar 27 11:21:28.141320 2017] [:error] [pid 19627] [remote ip1]   model.repo.commit()
[Mon Mar 27 11:21:28.141328 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/vdm/sqlalchemy/tools.py', line 107 in commit
[Mon Mar 27 11:21:28.141335 2017] [:error] [pid 19627] [remote ip1]   self.session.commit()
[Mon Mar 27 11:21:28.141342 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py', line 149 in do
[Mon Mar 27 11:21:28.141349 2017] [:error] [pid 19627] [remote ip1]   return getattr(self.registry(), name)(*args, **kwargs)
[Mon Mar 27 11:21:28.141356 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/session.py', line 768 in commit
[Mon Mar 27 11:21:28.141363 2017] [:error] [pid 19627] [remote ip1]   self.transaction.commit()
[Mon Mar 27 11:21:28.141370 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/session.py', line 370 in commit
[Mon Mar 27 11:21:28.141377 2017] [:error] [pid 19627] [remote ip1]   self._prepare_impl()
[Mon Mar 27 11:21:28.141384 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/session.py', line 339 in _prepare_impl
[Mon Mar 27 11:21:28.141391 2017] [:error] [pid 19627] [remote ip1]   self.session.dispatch.before_commit(self.session)
[Mon Mar 27 11:21:28.141398 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/event/attr.py', line 257 in __call__
[Mon Mar 27 11:21:28.141404 2017] [:error] [pid 19627] [remote ip1]   fn(*args, **kw)
[Mon Mar 27 11:21:28.141411 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/model/extension.py', line 112 in before_commit
[Mon Mar 27 11:21:28.141426 2017] [:error] [pid 19627] [remote ip1]   methodcaller('before_commit', session)
[Mon Mar 27 11:21:28.141433 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/model/extension.py', line 92 in notify_observers
[Mon Mar 27 11:21:28.141439 2017] [:error] [pid 19627] [remote ip1]   func(observer)
[Mon Mar 27 11:21:28.141445 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/model/modification.py', line 35 in before_commit
[Mon Mar 27 11:21:28.141472 2017] [:error] [pid 19627] [remote ip1]   self.notify_observers(session, self.notify)
[Mon Mar 27 11:21:28.141481 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/model/modification.py', line 77 in notify_observers
[Mon Mar 27 11:21:28.141488 2017] [:error] [pid 19627] [remote ip1]   method(obj, domain_object.DomainObjectOperation.changed)
[Mon Mar 27 11:21:28.141493 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/model/modification.py', line 84 in notify
[Mon Mar 27 11:21:28.141498 2017] [:error] [pid 19627] [remote ip1]   observer.notify(entity, operation)
[Mon Mar 27 11:21:28.141503 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/search/__init__.py', line 129 in notify
[Mon Mar 27 11:21:28.141508 2017] [:error] [pid 19627] [remote ip1]   operation
[Mon Mar 27 11:21:28.141513 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/search/__init__.py', line 103 in dispatch_by_operation
[Mon Mar 27 11:21:28.141517 2017] [:error] [pid 19627] [remote ip1]   index.update_dict(entity)
[Mon Mar 27 11:21:28.141532 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/search/index.py', line 103 in update_dict
[Mon Mar 27 11:21:28.141541 2017] [:error] [pid 19627] [remote ip1]   self.index_package(pkg_dict, defer_commit)
[Mon Mar 27 11:21:28.141548 2017] [:error] [pid 19627] [remote ip1] File '/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/search/index.py', line 288 in index_package
[Mon Mar 27 11:21:28.141556 2017] [:error] [pid 19627] [remote ip1]   raise SearchIndexError(msg)
[Mon Mar 27 11:21:28.141575 2017] [:error] [pid 19627] [remote ip1] SearchIndexError: Solr returned an error: 400 Illegal character ((CTRL-CHAR, code 1))  at [row,col {unknown-source}]: [6,1] - <html>
[Mon Mar 27 11:21:28.141591 2017] [:error] [pid 19627] [remote ip1] <head>
[Mon Mar 27 11:21:28.141598 2017] [:error] [pid 19627] [remote ip1] <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
[Mon Mar 27 11:21:28.141606 2017] [:error] [pid 19627] [remote ip1] <title>Error 400 Illegal character ((CTRL-CHAR, code 1))
[Mon Mar 27 11:21:28.141614 2017] [:error] [pid 19627] [remote ip1]  at [row,col {unknown-source}]: [6,1]</title>
[Mon Mar 27 11:21:28.141621 2017] [:error] [pid 19627] [remote ip1] </head>
[Mon Mar 27 11:21:28.141626 2017] [:error] [pid 19627] [remote ip1] <body><h2>HTTP ERROR 400</h2>
[Mon Mar 27 11:21:28.141630 2017] [:error] [pid 19627] [remote ip1] <p>Problem accessing /solr/update. Reason:
[Mon Mar 27 11:21:28.141635 2017] [:error] [pid 19627] [remote ip1] <pre>    Illegal character ((CTRL-CHAR, code 1))
[Mon Mar 27 11:21:28.141640 2017] [:error] [pid 19627] [remote ip1]  at [row,col {unknown-source}]: [6,1]</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>  
[Mon Mar 27 11:21:28.141655 2017] [:error] [pid 19627] [remote ip1] <br/>
[Mon Mar 27 11:21:28.141659 2017] [:error] [pid 19627] [remote ip1] <br/>
[Mon Mar 27 11:21:28.141665 2017] [:error] [pid 19627] [remote ip1] <br/>
[Mon Mar 27 11:21:28.141670 2017] [:error] [pid 19627] [remote ip1] <br/>
[Mon Mar 27 11:21:28.141675 2017] [:error] [pid 19627] [remote ip1] <br/>
[Mon Mar 27 11:21:28.141679 2017] [:error] [pid 19627] [remote ip1] <br/>
[Mon Mar 27 11:21:28.141684 2017] [:error] [pid 19627] [remote ip1] <br/>
[Mon Mar 27 11:21:28.141689 2017] [:error] [pid 19627] [remote ip1] <br/>
[Mon Mar 27 11:21:28.141693 2017] [:error] [pid 19627] [remote ip1]
[Mon Mar 27 11:21:28.141698 2017] [:error] [pid 19627] [remote ip1]
[Mon Mar 27 11:21:28.141703 2017] [:error] [pid 19627] [remote ip1] CGI Variables
[Mon Mar 27 11:21:28.141707 2017] [:error] [pid 19627] [remote ip1] -------------
[Mon Mar 27 11:21:28.141712 2017] [:error] [pid 19627] [remote ip1]   AUTH_TYPE: 'cookie'
[Mon Mar 27 11:21:28.141716 2017] [:error] [pid 19627] [remote ip1]   CKAN_CURRENT_URL: '/dataset/new_resource/plan-dzialania-pot-na-lata-2017-2018'


[Mon Mar 27 11:21:28.142252 2017] [:error] [pid 19627] [remote ip1] ------------------------------------------------------------
[Mon Mar 27 11:21:28.142263 2017] [:error] [pid 19627] [remote ip1]
[Mon Mar 27 11:21:28.142281 2017] [:error] [pid 19627] [remote ip1]             <p>Additionally an error occurred while sending the &lt;weberror.reporter.EmailReporter object at 0x7fa00f9d46d0&gt; report:
[Mon Mar 27 11:21:28.142287 2017] [:error] [pid 19627] [remote ip1]
[Mon Mar 27 11:21:28.142291 2017] [:error] [pid 19627] [remote ip1]             <pre>Traceback (most recent call last):
[Mon Mar 27 11:21:28.142296 2017] [:error] [pid 19627] [remote ip1]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/weberror/errormiddleware.py", line 450, in send_report
[Mon Mar 27 11:21:28.142301 2017] [:error] [pid 19627] [remote ip1]     rep.report(exc_data)
[Mon Mar 27 11:21:28.142305 2017] [:error] [pid 19627] [remote ip1]   File "/home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/weberror/reporter.py", line 45, in report
[Mon Mar 27 11:21:28.142310 2017] [:error] [pid 19627] [remote ip1]     server = smtplib.SMTP(self.smtp_server)
[Mon Mar 27 11:21:28.142315 2017] [:error] [pid 19627] [remote ip1]   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
[Mon Mar 27 11:21:28.142319 2017] [:error] [pid 19627] [remote ip1]     (code, msg) = self.connect(host, port)
[Mon Mar 27 11:21:28.142324 2017] [:error] [pid 19627] [remote ip1]   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
[Mon Mar 27 11:21:28.142329 2017] [:error] [pid 19627] [remote ip1]     self.sock = self._get_socket(host, port, self.timeout)
[Mon Mar 27 11:21:28.142334 2017] [:error] [pid 19627] [remote ip1]   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
[Mon Mar 27 11:21:28.142338 2017] [:error] [pid 19627] [remote ip1]     return socket.create_connection((host, port), timeout)
[Mon Mar 27 11:21:28.142343 2017] [:error] [pid 19627] [remote ip1]   File "/usr/lib/python2.7/socket.py", line 571, in create_connection
[Mon Mar 27 11:21:28.142347 2017] [:error] [pid 19627] [remote ip1]     raise err
[Mon Mar 27 11:21:28.142352 2017] [:error] [pid 19627] [remote ip1] error: [Errno 111] Connection refused
[Mon Mar 27 11:21:28.142356 2017] [:error] [pid 19627] [remote ip1] </pre>
[Mon Mar 27 11:21:28.152538 2017] [:error] [pid 19627] [remote ip1]             </p>
[Mon Mar 27 11:22:23.288047 2017] [:error] [pid 19627] 2017-03-27 11:22:23,287 ERROR [ckan.lib.search] Solr returned an error: 400 Illegal character ((CTRL-CHAR, code 1))  at [row,col {unknown-source}]: [6,1] - <html>

```

**Comment by KrzysztofMadejski** [comment]
Błąd pojawił się przy wgrywaniu [tego zasobu](https://danepubliczne.gov.pl/dataset/plan-dzialania-pot-lata-2017-2018/resource/fcc4d16a-6c23-4457-82b6-a6f922db01b8), ale udało się go wgrać.
