### ISSUE TITLE
cannot import name _uuid_generate_random

### ISSUE THREAD

**Issue by KrzysztofMadejski** [DanePubliczneGovPl/ckanext-danepubliczne#306]
```
(ckan) kmadejski@kmadejski-tecra:/home/ckan/src/ckan$ paster datastore set-permissions
Traceback (most recent call last):
  File "/home/kmadejski/.virtualenvs/ckan/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/home/kmadejski/.virtualenvs/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/home/kmadejski/.virtualenvs/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/home/kmadejski/.virtualenvs/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/home/kmadejski/.virtualenvs/ckan/src/ckan/ckanext/datastore/commands.py", line 70, in command
    self._load_config()
  File "/home/kmadejski/.virtualenvs/ckan/src/ckan/ckan/lib/cli.py", line 148, in _load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/home/kmadejski/.virtualenvs/ckan/src/ckan/ckan/config/environment.py", line 232, in load_environment
    p.load_all(config)
  File "/home/kmadejski/.virtualenvs/ckan/src/ckan/ckan/plugins/core.py", line 134, in load_all
    load(*plugins)
  File "/home/kmadejski/.virtualenvs/ckan/src/ckan/ckan/plugins/core.py", line 148, in load
    service = _get_service(plugin)
  File "/home/kmadejski/.virtualenvs/ckan/src/ckan/ckan/plugins/core.py", line 254, in _get_service
    return plugin.load()(name=plugin_name)
  File "/home/kmadejski/.virtualenvs/ckan/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/kmadejski/.virtualenvs/ckan/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kmadejski/.virtualenvs/ckan/src/ckanext-danepubliczne/ckanext/danepubliczne/schema/__init__.py", line 5, in <module>
    from dataset import DatasetForm
  File "/home/kmadejski/.virtualenvs/ckan/src/ckanext-danepubliczne/ckanext/danepubliczne/schema/dataset.py", line 13, in <module>
    from ckanext.qa.plugin import QAPlugin
  File "/home/kmadejski/.virtualenvs/ckan/src/ckanext-qa/ckanext/qa/plugin.py", line 11, in <module>
    from ckanext.qa import lib
  File "/home/kmadejski/.virtualenvs/ckan/src/ckanext-qa/ckanext/qa/lib.py", line 9, in <module>
    from ckan.lib.celery_app import celery
  File "/home/kmadejski/.virtualenvs/ckan/src/ckan/ckan/lib/celery_app.py", line 14, in <module>
    celery = Celery()
  File "/home/kmadejski/.virtualenvs/ckan/local/lib/python2.7/site-packages/celery/__init__.py", line 26, in Celery
    from .app import App
  File "/home/kmadejski/.virtualenvs/ckan/local/lib/python2.7/site-packages/celery/app/__init__.py", line 22, in <module>
    from ..utils import cached_property, instantiate
  File "/home/kmadejski/.virtualenvs/ckan/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 31, in <module>
    from kombu.utils import cached_property, gen_unique_id  # noqa
  File "/home/kmadejski/.virtualenvs/ckan/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 17, in <module>
    from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
ImportError: cannot import name _uuid_generate_random
```

Happening with Kombu 2.5.0 and Python 2.7.11, has been fixed in Kombu 3.0.30: https://github.com/celery/kombu/issues/545. With Python 2.7.6 works ok.

**Comment by KrzysztofMadejski** [comment]
Related to https://github.com/ckan/ckanext-qa/issues/43
